### ISSUE TITLE
Need a license file

### ISSUE THREAD

**Issue by kgambrel** [fxnut/siLib#15]
I work for Disney Animation Studios.  We're interested in evaluating and perhaps using this library, but we require a license file to be included in the repository.  The license file should include a copyright statement.

We prefer that the license is one of the standard ones from opensource.org/licenses, but you can, of course, roll your own.   

Cheers.

**Comment by fxnut** [comment]
Hi Kevin, thanks for reminding me. Have just added (#16) a license file for siLib under GNU General Public License v3.0.

Hope that works for you.

**Comment by kgambrel** [comment]
GPL V3 is fine with us.

**Comment by kgambrel** [comment]
Oh, and thanks for the quick response.
Cheers.
